/* Generated By:JavaCC: Do not edit this line. AnalizadorSemanticoConstants.java */
package  analizadorSemantico;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSemanticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MODIFICADOR = 5;
  /** RegularExpression Id. */
  int CLASE = 6;
  /** RegularExpression Id. */
  int TIPO = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int SI = 9;
  /** RegularExpression Id. */
  int MIENTTRAS = 10;
  /** RegularExpression Id. */
  int PARENTESIS_IZQ = 11;
  /** RegularExpression Id. */
  int PARENTESIS_DER = 12;
  /** RegularExpression Id. */
  int CORCHETE_IZQ = 13;
  /** RegularExpression Id. */
  int CORCHETE_DER = 14;
  /** RegularExpression Id. */
  int PUNTO_Y_COMA = 15;
  /** RegularExpression Id. */
  int COMA = 16;
  /** RegularExpression Id. */
  int PUNTO = 17;
  /** RegularExpression Id. */
  int NEGACION = 18;
  /** RegularExpression Id. */
  int OPERADOR = 19;
  /** RegularExpression Id. */
  int ASIGNACION = 20;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO = 21;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO = 22;
  /** RegularExpression Id. */
  int OPERADOR_UNARIO = 23;
  /** RegularExpression Id. */
  int LITERAL_ENTERA = 24;
  /** RegularExpression Id. */
  int LITERAL_BOOLEANA = 25;
  /** RegularExpression Id. */
  int LITERAL_CADENA = 26;
  /** RegularExpression Id. */
  int LITERAL_DOBLE = 27;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<MODIFICADOR>",
    "\"class\"",
    "<TIPO>",
    "\"void\"",
    "\"if\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"-\"",
    "<OPERADOR>",
    "\"=\"",
    "<OPERADOR_LOGICO>",
    "<OPERADOR_ARITMETICO>",
    "\"!\"",
    "<LITERAL_ENTERA>",
    "<LITERAL_BOOLEANA>",
    "<LITERAL_CADENA>",
    "<LITERAL_DOBLE>",
    "<IDENTIFICADOR>",
  };

}
